Repository ron2111/Hacktoberfest2021_awesome-projects, pull requests merged in 2021-09, with the labels that each got.

#13 Update Project_doc.md
  Unique C++ Projects/Project_doc.md
Labels: documentation, hacktoberfest-accepted

#14 Described the project
  ML Projects/Project_doc.md
Labels: documentation, hacktoberfest-accepted

#9 Added Drowsiness Detection Project
  NewDrowsiness/DrowsinessDetector.py
  NewDrowsiness/alarm.wav
  NewDrowsiness/haarcascade_eye.xml
  NewDrowsiness/haarcascade_frontalface_default.xml
  NewDrowsiness/haarcascade_lefteye_2splits.xml
  NewDrowsiness/haarcascade_righteye_2splits.xml
  README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#6 Added 7 Segment Display
  Unique C++ Projects/7-Segment-Display.cpp
  Web Dev Projects_or_Portfolios/Trickaza/assets/img/Cricket.png
  Web Dev Projects_or_Portfolios/Trickaza/assets/img/Slot 1.png
  Web Dev Projects_or_Portfolios/Trickaza/assets/img/Slot 2.png
  Web Dev Projects_or_Portfolios/Trickaza/assets/img/Slot 3.png
  Web Dev Projects_or_Portfolios/Trickaza/assets/img/Slot 4.png
  Web Dev Projects_or_Portfolios/Trickaza/assets/img/Slot 5.png
  Web Dev Projects_or_Portfolios/Trickaza/assets/img/Slot 6.png
  Web Dev Projects_or_Portfolios/Trickaza/assets/img/Slot 7.png
  Web Dev Projects_or_Portfolios/Trickaza/assets/img/Slots BG.png
  Web Dev Projects_or_Portfolios/Trickaza/assets/img/Trickaza.png
  Web Dev Projects_or_Portfolios/Trickaza/css/body.css
  Web Dev Projects_or_Portfolios/Trickaza/css/heading.css
  Web Dev Projects_or_Portfolios/Trickaza/css/styles.css
  Web Dev Projects_or_Portfolios/Trickaza/index.html
  Web Dev Projects_or_Portfolios/Trickaza/js/scripts.js
Labels: hacktoberfest, hacktoberfest-accepted

#22 updated readme.md
  README.md
Labels: documentation

#29 Update readme.md
  README.md
Labels: documentation, hacktoberfest-accepted

#7 Adding a python script to send mails automatedly
  Amazing Python Projects_Scripts/Mailing scripts/README.md
  Amazing Python Projects_Scripts/Mailing scripts/mail-script.py
  Amazing Python Projects_Scripts/mail-script.py
Labels: documentation, enhancement, hacktoberfest, hacktoberfest-accepted

#27 feat: Add github dp loader javascript project
  Awesome Javascript Projects_Scripts/Project_doc.md
  Awesome Javascript Projects_Scripts/github-dp-using-axios/index.html
  README.md
Labels: hacktoberfest-accepted

#34 Update README.md
  README.md
Labels: documentation

#39 added stock market simulator and updated project_doc.md
  Web Dev Projects_or_Portfolios/Project_doc.md
  Web Dev Projects_or_Portfolios/Stock Market Simulator/client/.gitignore
  Web Dev Projects_or_Portfolios/Stock Market Simulator/client/package-lock.json
  Web Dev Projects_or_Portfolios/Stock Market Simulator/client/package.json
  Web Dev Projects_or_Portfolios/Stock Market Simulator/client/public/index.html
  Web Dev Projects_or_Portfolios/Stock Market Simulator/client/public/manifest.json
  Web Dev Projects_or_Portfolios/Stock Market Simulator/client/public/robots.txt
  Web Dev Projects_or_Portfolios/Stock Market Simulator/client/src/App.css
  Web Dev Projects_or_Portfolios/Stock Market Simulator/client/src/App.js
  Web Dev Projects_or_Portfolios/Stock Market Simulator/client/src/App.test.js
  Web Dev Projects_or_Portfolios/Stock Market Simulator/client/src/index.css
  Web Dev Projects_or_Portfolios/Stock Market Simulator/client/src/index.js
  Web Dev Projects_or_Portfolios/Stock Market Simulator/client/src/reportWebVitals.js
  Web Dev Projects_or_Portfolios/Stock Market Simulator/client/src/setupTests.js
Labels: documentation, hacktoberfest-accepted

#23 Simple portfolio website
  App Dev Based Projects/news_app/README.md
  App Dev Based Projects/news_app/app/build.gradle
  App Dev Based Projects/news_app/app/proguard-rules.pro
  App Dev Based Projects/news_app/app/src/androidTest/java/com/example/android/news_app/ExampleInstrumentedTest.java
  App Dev Based Projects/news_app/app/src/main/AndroidManifest.xml
  App Dev Based Projects/news_app/app/src/main/java/com/example/android/news_app/MainActivity.java
  App Dev Based Projects/news_app/app/src/main/java/com/example/android/news_app/MySingleton.java
  App Dev Based Projects/news_app/app/src/main/java/com/example/android/news_app/NewsAdapters.java
  App Dev Based Projects/news_app/app/src/main/java/com/example/android/news_app/news.java
  App Dev Based Projects/news_app/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  App Dev Based Projects/news_app/app/src/main/res/drawable/ic_launcher_background.xml
  App Dev Based Projects/news_app/app/src/main/res/layout/activity_main.xml
  App Dev Based Projects/news_app/app/src/main/res/layout/item_news.xml
  App Dev Based Projects/news_app/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  App Dev Based Projects/news_app/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  App Dev Based Projects/news_app/app/src/main/res/mipmap-hdpi/ic_launcher.png
  App Dev Based Projects/news_app/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  App Dev Based Projects/news_app/app/src/main/res/mipmap-mdpi/ic_launcher.png
  App Dev Based Projects/news_app/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  App Dev Based Projects/news_app/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  App Dev Based Projects/news_app/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  App Dev Based Projects/news_app/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  App Dev Based Projects/news_app/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  App Dev Based Projects/news_app/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  App Dev Based Projects/news_app/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  App Dev Based Projects/news_app/app/src/main/res/values-night/themes.xml
  App Dev Based Projects/news_app/app/src/main/res/values/colors.xml
  App Dev Based Projects/news_app/app/src/main/res/values/strings.xml
  App Dev Based Projects/news_app/app/src/main/res/values/themes.xml
  App Dev Based Projects/news_app/app/src/test/java/com/example/android/news_app/ExampleUnitTest.java
  App Dev Based Projects/news_app/build.gradle
  App Dev Based Projects/news_app/gradle.properties
  App Dev Based Projects/news_app/gradle/wrapper/gradle-wrapper.jar
  App Dev Based Projects/news_app/gradle/wrapper/gradle-wrapper.properties
  App Dev Based Projects/news_app/gradlew
  App Dev Based Projects/news_app/gradlew.bat
  App Dev Based Projects/news_app/settings.gradle
  README.md
  Web Dev Projects_or_Portfolios/Simple_Portfolio_website-master/README.md
  Web Dev Projects_or_Portfolios/Simple_Portfolio_website-master/css/bootstrap.min.css
  Web Dev Projects_or_Portfolios/Simple_Portfolio_website-master/css/contact.css
  Web Dev Projects_or_Portfolios/Simple_Portfolio_website-master/css/global.css
  Web Dev Projects_or_Portfolios/Simple_Portfolio_website-master/css/magnific-popup.css
  Web Dev Projects_or_Portfolios/Simple_Portfolio_website-master/global.html
  Web Dev Projects_or_Portfolios/Simple_Portfolio_website-master/index.html
  Web Dev Projects_or_Portfolios/Simple_Portfolio_website-master/portfolio.html
  Web Dev Projects_or_Portfolios/Simple_Portfolio_website-master/profile.html
  Web Dev Projects_or_Portfolios/Simple_Portfolio_website-master/resume.html
Labels: hacktoberfest-accepted, Great

#52 Adding a Stock Price Predicition ML Model
  ML Projects/LSTM_Stock_Prediction_Model.ipynb
Labels: hacktoberfest-accepted, Great

#53 Update Project_doc.md
  ML Projects/Project_doc.md
Labels: documentation

#57 Adding a simple calculator in JavaScript
  Awesome Javascript Projects_Scripts/Basic Calculator/index.html
  Awesome Javascript Projects_Scripts/Basic Calculator/src/script.js
  Awesome Javascript Projects_Scripts/Basic Calculator/src/styles.css
  Awesome Javascript Projects_Scripts/Project_doc.md
  README.md
Labels: documentation, good first issue, hacktoberfest-accepted

#46 Budget manager chrome extension added
  Web Dev Projects_or_Portfolios/BUDGET MANAGER/icon128.png
  Web Dev Projects_or_Portfolios/BUDGET MANAGER/icon16.png
  Web Dev Projects_or_Portfolios/BUDGET MANAGER/icon48.png
  Web Dev Projects_or_Portfolios/BUDGET MANAGER/jquery-3.6.0.min.js
  Web Dev Projects_or_Portfolios/BUDGET MANAGER/manifest.json
  Web Dev Projects_or_Portfolios/BUDGET MANAGER/options.html
  Web Dev Projects_or_Portfolios/BUDGET MANAGER/options.js
  Web Dev Projects_or_Portfolios/BUDGET MANAGER/popup.html
  Web Dev Projects_or_Portfolios/BUDGET MANAGER/popup.js
  Web Dev Projects_or_Portfolios/BUDGET MANAGER/readme.md
  Web Dev Projects_or_Portfolios/Project_doc.md
Labels: hacktoberfest-accepted, Nicely Done

#64 YT Dataset
  Awesome Javascript Projects_Scripts/Project_doc.md
  Awesome Javascript Projects_Scripts/YT-GetDataSet/dataset.js
  README.md
Labels: hacktoberfest-accepted

#54 add simon color game in js
  Awesome Javascript Projects_Scripts/simon-color-game/README.md
  Awesome Javascript Projects_Scripts/simon-color-game/fav.ico
  Awesome Javascript Projects_Scripts/simon-color-game/index.html
  Awesome Javascript Projects_Scripts/simon-color-game/index.js
  Awesome Javascript Projects_Scripts/simon-color-game/sounds/blue.mp3
  Awesome Javascript Projects_Scripts/simon-color-game/sounds/green.mp3
  Awesome Javascript Projects_Scripts/simon-color-game/sounds/red.mp3
  Awesome Javascript Projects_Scripts/simon-color-game/sounds/wrong.mp3
  Awesome Javascript Projects_Scripts/simon-color-game/sounds/yellow.mp3
  Awesome Javascript Projects_Scripts/simon-color-game/styles.css
Labels: hacktoberfest-accepted

#68 Update Project_doc.md
  Web Dev Projects_or_Portfolios/Project_doc.md
Labels: hacktoberfest-accepted
