Repository ron2111/Hacktoberfest2021_awesome-projects, pull requests merged in 2021-10, with the labels that each got.

#81 Added my Web Development project ( issue #8 )
  README.md
  Web Dev Projects_or_Portfolios/CSS-Grid-Animated-Tiles-with-Toggle-switch/index.html
  Web Dev Projects_or_Portfolios/CSS-Grid-Animated-Tiles-with-Toggle-switch/script.js
  Web Dev Projects_or_Portfolios/CSS-Grid-Animated-Tiles-with-Toggle-switch/styles.css
  Web Dev Projects_or_Portfolios/Project_doc.md
Labels: hacktoberfest-accepted, Nicely Done

#94 create bubble-sort.cpp
  Unique C++ Projects/bubble-sort.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#95 craeting javascript framework or library project folder
  Javascript framework And Library project/Angular.js/Project_doc.md
  Javascript framework And Library project/Angular2+/Project_doc.md
  Javascript framework And Library project/React.js/Project_doc.md
  Javascript framework And Library project/Vue.js/Project_doc.md
Labels: hacktoberfest-accepted

#100 Patch 4
  Web Dev Projects_or_Portfolios/Current weather web app/index.html
  Web Dev Projects_or_Portfolios/Current weather web app/style.css
Labels: enhancement, hacktoberfest-accepted

#108 Breast Cancer Prediction (ML Project)
  ML Projects/Breast Cancer Prediction/README.md
  ML Projects/Breast Cancer Prediction/breast_cancer_prediction.py
  ML Projects/Project_doc.md
  README.md
Labels: hacktoberfest-accepted, Great, Nicely Done

#110 Tic tac toe
  README.md
  Unique C++ Projects/Project_doc.md
  Unique C++ Projects/Tic_Tac_Toe.cpp
Labels: documentation, hacktoberfest-accepted, Great

#115 E commerce MERN Website by Rohan Gupta
  README.md
  Web Dev Projects_or_Portfolios/E Commerce App/README.md
  Web Dev Projects_or_Portfolios/E Commerce App/backend/index.js
  Web Dev Projects_or_Portfolios/E Commerce App/frontend/.gitignore
  Web Dev Projects_or_Portfolios/E Commerce App/frontend/README.md
  Web Dev Projects_or_Portfolios/E Commerce App/frontend/package-lock.json
  Web Dev Projects_or_Portfolios/E Commerce App/frontend/package.json
  Web Dev Projects_or_Portfolios/E Commerce App/frontend/public/favicon.ico
  Web Dev Projects_or_Portfolios/E Commerce App/frontend/public/index.html
  Web Dev Projects_or_Portfolios/E Commerce App/frontend/public/logo192.png
  Web Dev Projects_or_Portfolios/E Commerce App/frontend/public/logo512.png
  Web Dev Projects_or_Portfolios/E Commerce App/frontend/public/manifest.json
  Web Dev Projects_or_Portfolios/E Commerce App/frontend/public/robots.txt
  Web Dev Projects_or_Portfolios/E Commerce App/frontend/src/App.css
  Web Dev Projects_or_Portfolios/E Commerce App/frontend/src/App.js
  Web Dev Projects_or_Portfolios/E Commerce App/frontend/src/App.test.js
  Web Dev Projects_or_Portfolios/E Commerce App/frontend/src/index.css
  Web Dev Projects_or_Portfolios/E Commerce App/frontend/src/index.js
  Web Dev Projects_or_Portfolios/E Commerce App/frontend/src/logo.svg
  Web Dev Projects_or_Portfolios/E Commerce App/frontend/src/reportWebVitals.js
  Web Dev Projects_or_Portfolios/E Commerce App/frontend/src/setupTests.js
  Web Dev Projects_or_Portfolios/Project_doc.md
Labels: hacktoberfest, hacktoberfest-accepted, Great

#98 Added converting live camera video stream into cartoon effect
  Amazing Python Projects_Scripts/Project_doc.md
  Amazing Python Projects_Scripts/webcamCartoon.py
  README.md
Labels: hacktoberfest, hacktoberfest-accepted, Great

#92 Prannov ML Project
  ML Projects/READMEproject.md
  ML Projects/iris_classification.ipynb
  README.md
Labels: hacktoberfest, hacktoberfest-accepted, Great

#37 Create Fidget Spinner.py
  Amazing Python Projects_Scripts/Fidget Spinner/Fidget Spinner.py
  Amazing Python Projects_Scripts/Project_doc.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#125 Youtube UI Clone using HTML, CSS and JS
  Youtube-Clone/README.md
  Youtube-Clone/Resources/favicon_32x32.png
  Youtube-Clone/Resources/youtube_logo.png
  Youtube-Clone/Resources/youtube_logo.webp
  Youtube-Clone/css/styles.css
  Youtube-Clone/index.html
Labels: hacktoberfest-accepted, Great, Nicely Done

#133 Added Photo Site
  Web Dev Projects_or_Portfolios/Photo Site/index.html
  Web Dev Projects_or_Portfolios/Photo Site/photo_site.css
  Web Dev Projects_or_Portfolios/Project_doc.md
Labels: hacktoberfest, hacktoberfest-accepted, Great

#114 Redesigned the Navbar in the Existing Project
  Web Dev Projects_or_Portfolios/CSS-Grid-Animated-Tiles-with-Toggle-switch/index.html
Labels: hacktoberfest, hacktoberfest-accepted, Great

#139 Binary to Decimal convertor
  README.md
  Unique C++ Projects/BinaryToDecimal.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#69 GAN for Generating MNIST Handwritten Digits
  ML Projects/Generating MNIST Handwritten Digits.ipynb
  ML Projects/Project_doc.md
  Stunning clones/Youtube-Clone/README.md
  Stunning clones/Youtube-Clone/Resources/favicon_32x32.png
  Stunning clones/Youtube-Clone/Resources/youtube_logo.png
  Stunning clones/Youtube-Clone/Resources/youtube_logo.webp
  Stunning clones/Youtube-Clone/css/styles.css
  Stunning clones/Youtube-Clone/index.html
  Stunning clones/project_doc.md
Labels: hacktoberfest, hacktoberfest-accepted, Great

#158 🚀Added Age Calculator
  Web Dev Projects_or_Portfolios/Age Calculator/index.html
  Web Dev Projects_or_Portfolios/Age Calculator/index.js
  Web Dev Projects_or_Portfolios/Age Calculator/readme.md
  Web Dev Projects_or_Portfolios/Age Calculator/style.css
  Web Dev Projects_or_Portfolios/Project_doc.md
Labels: hacktoberfest, hacktoberfest-accepted, Great

#28 added: TextUtils Web-App (by casafurix)
  README.md
  Web Dev Projects_or_Portfolios/Project_doc.md
  Web Dev Projects_or_Portfolios/TextUtils Web-App/README.md
  Web Dev Projects_or_Portfolios/TextUtils Web-App/package-lock.json
  Web Dev Projects_or_Portfolios/TextUtils Web-App/package.json
  Web Dev Projects_or_Portfolios/TextUtils Web-App/public/index.html
  Web Dev Projects_or_Portfolios/TextUtils Web-App/public/manifest.json
  Web Dev Projects_or_Portfolios/TextUtils Web-App/public/notes.png
  Web Dev Projects_or_Portfolios/TextUtils Web-App/public/robots.txt
  Web Dev Projects_or_Portfolios/TextUtils Web-App/src/App.css
  Web Dev Projects_or_Portfolios/TextUtils Web-App/src/App.js
  Web Dev Projects_or_Portfolios/TextUtils Web-App/src/App.test.js
  Web Dev Projects_or_Portfolios/TextUtils Web-App/src/components/About.js
  Web Dev Projects_or_Portfolios/TextUtils Web-App/src/components/Alert.js
  Web Dev Projects_or_Portfolios/TextUtils Web-App/src/components/Navbar.js
  Web Dev Projects_or_Portfolios/TextUtils Web-App/src/components/TextForm.js
  Web Dev Projects_or_Portfolios/TextUtils Web-App/src/index.css
  Web Dev Projects_or_Portfolios/TextUtils Web-App/src/index.js
  Web Dev Projects_or_Portfolios/TextUtils Web-App/src/logo.svg
  Web Dev Projects_or_Portfolios/TextUtils Web-App/src/reportWebVitals.js
  Web Dev Projects_or_Portfolios/TextUtils Web-App/src/setupTests.js
Labels: hacktoberfest, hacktoberfest-accepted, Great

#124 Adding Real Estate Price Prediction Project.
  ML Projects/Project_doc.md
  ML Projects/Real Estate Price Prediction project/README.md
  ML Projects/Real Estate Price Prediction project/real_estate_price_prediction.ipynb
  README.md
Labels: hacktoberfest-accepted, Nicely Done

#164 🚀Added Chess Clone
  Stunning Clones/Chess Clone/README.md
  Stunning Clones/Chess Clone/app.js
  Stunning Clones/Chess Clone/index.html
  Stunning Clones/Chess Clone/style.css
  Stunning Clones/Project_doc.md
  Stunning Clones/Youtube-Clone/README.md
  Stunning Clones/Youtube-Clone/Resources/favicon_32x32.png
  Stunning Clones/Youtube-Clone/Resources/youtube_logo.png
  Stunning Clones/Youtube-Clone/Resources/youtube_logo.webp
  Stunning Clones/Youtube-Clone/css/styles.css
  Stunning Clones/Youtube-Clone/index.html
Labels: hacktoberfest, hacktoberfest-accepted, Great

#128 Added Web Development Project- News App
  README.md
  Web Dev Projects_or_Portfolios/NewsApp/.gitignore
  Web Dev Projects_or_Portfolios/NewsApp/README.md
  Web Dev Projects_or_Portfolios/NewsApp/Screenshots/category.png
  Web Dev Projects_or_Portfolios/NewsApp/Screenshots/general.png
  Web Dev Projects_or_Portfolios/NewsApp/Screenshots/search.png
  Web Dev Projects_or_Portfolios/NewsApp/package-lock.json
  Web Dev Projects_or_Portfolios/NewsApp/package.json
  Web Dev Projects_or_Portfolios/NewsApp/public/altImage.jpg
  Web Dev Projects_or_Portfolios/NewsApp/public/favicon.ico
  Web Dev Projects_or_Portfolios/NewsApp/public/index.html
  Web Dev Projects_or_Portfolios/NewsApp/public/loader.gif
  Web Dev Projects_or_Portfolios/NewsApp/public/logo192.png
  Web Dev Projects_or_Portfolios/NewsApp/public/logo512.png
  Web Dev Projects_or_Portfolios/NewsApp/public/manifest.json
  Web Dev Projects_or_Portfolios/NewsApp/public/robots.txt
  Web Dev Projects_or_Portfolios/NewsApp/src/App.js
  Web Dev Projects_or_Portfolios/NewsApp/src/apis/countries.js
  Web Dev Projects_or_Portfolios/NewsApp/src/apis/newsapi.js
  Web Dev Projects_or_Portfolios/NewsApp/src/components/Loader.js
  Web Dev Projects_or_Portfolios/NewsApp/src/components/NavBar.js
  Web Dev Projects_or_Portfolios/NewsApp/src/components/News.js
  Web Dev Projects_or_Portfolios/NewsApp/src/components/NewsItem.js
  Web Dev Projects_or_Portfolios/NewsApp/src/index.js
  Web Dev Projects_or_Portfolios/Project_doc.md
Labels: hacktoberfest, hacktoberfest-accepted

#161 Added A Red object Identifying Script
  Amazing Python Projects_Scripts/Project_doc.md
  Amazing Python Projects_Scripts/Red object Identifier/Images/ClockInside.png
  Amazing Python Projects_Scripts/Red object Identifier/Images/NikeImg.png
  Amazing Python Projects_Scripts/Red object Identifier/app.py
Labels: hacktoberfest, hacktoberfest-accepted, Great

#162 Add Typing-master-website project
  Awesome Javascript Projects_Scripts/Random_Quote_Generator/README.md
  Awesome Javascript Projects_Scripts/Random_Quote_Generator/images/logo.png
  Awesome Javascript Projects_Scripts/Random_Quote_Generator/index.html
  Awesome Javascript Projects_Scripts/Random_Quote_Generator/index.js
  Awesome Javascript Projects_Scripts/Typing-master-website/README.md
  Awesome Javascript Projects_Scripts/Typing-master-website/css/style.css
  Awesome Javascript Projects_Scripts/Typing-master-website/index.html
  Awesome Javascript Projects_Scripts/Typing-master-website/script/script.js
Labels: hacktoberfest, hacktoberfest-accepted

#206 Personal portfolio website added
  README.md
  Web Dev Projects_or_Portfolios/Personal-portfolio-website/README.md
  Web Dev Projects_or_Portfolios/Personal-portfolio-website/images/favicon.png
  Web Dev Projects_or_Portfolios/Personal-portfolio-website/images/portfolio-bg.jpeg
  Web Dev Projects_or_Portfolios/Personal-portfolio-website/index.html
  Web Dev Projects_or_Portfolios/Personal-portfolio-website/style.css
  Web Dev Projects_or_Portfolios/Project_doc.md
Labels: hacktoberfest, hacktoberfest-accepted

#199 Added Game of Life in React
  Javascript framework And Library project/React.js/Project_doc.md
  Javascript framework And Library project/React.js/game-of-life/README.md
  Javascript framework And Library project/React.js/game-of-life/package-lock.json
  Javascript framework And Library project/React.js/game-of-life/package.json
  Javascript framework And Library project/React.js/game-of-life/public/game_of_life.jpg
  Javascript framework And Library project/React.js/game-of-life/public/index.html
  Javascript framework And Library project/React.js/game-of-life/public/manifest.json
  Javascript framework And Library project/React.js/game-of-life/server.js
  Javascript framework And Library project/React.js/game-of-life/src/App.js
  Javascript framework And Library project/React.js/game-of-life/src/index.js
  Javascript framework And Library project/React.js/game-of-life/src/index.scss
  Javascript framework And Library project/React.js/game-of-life/src/serviceWorker.js
  Stunning Clones/Project_doc.md
Labels: hacktoberfest, hacktoberfest-accepted

#62 data science modelling project
  ML Projects/DataScience/BAYESIAN AND GMM.ipynb
  ML Projects/DataScience/Batch06 (1).csv
  ML Projects/DataScience/Descriptive Analysis (2).ipynb
  ML Projects/DataScience/KNN.ipynb
  ML Projects/Project_doc.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted, Great

#217 Uploaded my portfolio
  Incredible Java Projects/calculator.java
  Web Dev Projects_or_Portfolios/Imrantechwiz-Portfolio/Readme.md
  Web Dev Projects_or_Portfolios/Imrantechwiz-Portfolio/ext.js
  Web Dev Projects_or_Portfolios/Imrantechwiz-Portfolio/index.html
  Web Dev Projects_or_Portfolios/Imrantechwiz-Portfolio/photos/MPIC.jpg
  Web Dev Projects_or_Portfolios/Imrantechwiz-Portfolio/photos/imgbanner.jpg
  Web Dev Projects_or_Portfolios/Imrantechwiz-Portfolio/photos/res.pdf
  Web Dev Projects_or_Portfolios/Imrantechwiz-Portfolio/style.css
Labels: hacktoberfest-accepted

#213 adding social network project
  Web Dev Projects_or_Portfolios/Project_doc.md
  Web Dev Projects_or_Portfolios/socialnetwork/.gitignore
  Web Dev Projects_or_Portfolios/socialnetwork/README.md
  Web Dev Projects_or_Portfolios/socialnetwork/config/database.js
  Web Dev Projects_or_Portfolios/socialnetwork/config/passport.js
  Web Dev Projects_or_Portfolios/socialnetwork/controllers/auth.js
  Web Dev Projects_or_Portfolios/socialnetwork/controllers/home.js
  Web Dev Projects_or_Portfolios/socialnetwork/controllers/posts.js
  Web Dev Projects_or_Portfolios/socialnetwork/middleware/auth.js
  Web Dev Projects_or_Portfolios/socialnetwork/middleware/multer.js
  Web Dev Projects_or_Portfolios/socialnetwork/models/Post.js
  Web Dev Projects_or_Portfolios/socialnetwork/models/User.js
  Web Dev Projects_or_Portfolios/socialnetwork/package-lock.json
  Web Dev Projects_or_Portfolios/socialnetwork/package.json
  Web Dev Projects_or_Portfolios/socialnetwork/public/css/style.css
  Web Dev Projects_or_Portfolios/socialnetwork/public/imgs/favicon-32x32.png
  Web Dev Projects_or_Portfolios/socialnetwork/public/imgs/favicon.ico
  Web Dev Projects_or_Portfolios/socialnetwork/public/uploads/02176bda1920c668b61fc776772d240d
  Web Dev Projects_or_Portfolios/socialnetwork/public/uploads/6e029a3bd20c492a247cc78fca10d120
  Web Dev Projects_or_Portfolios/socialnetwork/public/uploads/c81ff45ec593c949fb241dddc59f7cb0
  Web Dev Projects_or_Portfolios/socialnetwork/routes/main.js
  Web Dev Projects_or_Portfolios/socialnetwork/routes/posts.js
  Web Dev Projects_or_Portfolios/socialnetwork/server.js
  Web Dev Projects_or_Portfolios/socialnetwork/views/feed.ejs
  Web Dev Projects_or_Portfolios/socialnetwork/views/index.ejs
  Web Dev Projects_or_Portfolios/socialnetwork/views/login.ejs
  Web Dev Projects_or_Portfolios/socialnetwork/views/partials/footer.ejs
  Web Dev Projects_or_Portfolios/socialnetwork/views/partials/header.ejs
  Web Dev Projects_or_Portfolios/socialnetwork/views/post.ejs
  Web Dev Projects_or_Portfolios/socialnetwork/views/profile.ejs
  Web Dev Projects_or_Portfolios/socialnetwork/views/signup.ejs
Labels: hacktoberfest-accepted

#180 Scan and Generate QR Code
  Amazing Python Projects_Scripts/Project_doc.md
  Amazing Python Projects_Scripts/Scan and Generate QR Code/Scan_Generate_QR_Code.py
  README.md
Labels: hacktoberfest-accepted, Nicely Done

#220 Added Script to Automate Folder Files and updated the necessary docs
  Amazing Python Projects_Scripts/Folder-Automator/automate_folder.py
  Amazing Python Projects_Scripts/Project_doc.md
Labels: hacktoberfest-accepted

#208 Added GUI based calculator
  Amazing Python Projects_Scripts/GUI calculator.py
Labels: hacktoberfest-accepted

#207 Online Compiler
  Web Dev Projects_or_Portfolios/Online Compiler/index.html
  Web Dev Projects_or_Portfolios/Online Compiler/readme.md
Labels: hacktoberfest-accepted

#211 Amazom Prime Video Login Page Clone
  Web Dev Projects_or_Portfolios/Amazon-Prime-Login-Page-Clone/README.md
  Web Dev Projects_or_Portfolios/Amazon-Prime-Login-Page-Clone/index.css
  Web Dev Projects_or_Portfolios/Amazon-Prime-Login-Page-Clone/index.html
Labels: hacktoberfest-accepted

#131 Added Basic Background Generator Project
  Basic Background Generator/Readme.md
  Basic Background Generator/index.html
  Basic Background Generator/script.js
  Basic Background Generator/style.css
Labels: hacktoberfest-accepted

#198 car game project add
  Awesome Javascript Projects_Scripts/CAR-GAME-project/README.md
  Awesome Javascript Projects_Scripts/CAR-GAME-project/css/style.css
  Awesome Javascript Projects_Scripts/CAR-GAME-project/index.html
  Awesome Javascript Projects_Scripts/CAR-GAME-project/music/main_song.mp3
  Awesome Javascript Projects_Scripts/CAR-GAME-project/script/script.js
  Stunning clones/project_doc.md
Labels: hacktoberfest-accepted, Great

#192 Internshala Clone
  Amazing Python Projects_Scripts/Password_generator/14.jpg
  Amazing Python Projects_Scripts/Password_generator/Demo.PNG
  Amazing Python Projects_Scripts/Password_generator/password_generator.py
  Stunning Clones/Internshala_Clone/README.md
  Stunning Clones/Internshala_Clone/index.css
  Stunning Clones/Internshala_Clone/index.html
  Stunning Clones/Internshala_Clone/index.php
  Stunning Clones/Internshala_Clone/nev_bar.js
Labels: hacktoberfest-accepted, Great

#221 Added the necessary information.
  ML Projects/Transfer_Learning_Face_Detection/README.md
  ML Projects/Transfer_Learning_Face_Detection/Transfer learning with ResNet.py
Labels: hacktoberfest-accepted

#159 resturant confusion add
  Web Dev Projects_or_Portfolios/restaurant Confusion/.DS_Store
  Web Dev Projects_or_Portfolios/restaurant Confusion/.gitignore
  Web Dev Projects_or_Portfolios/restaurant Confusion/aboutus.html
  Web Dev Projects_or_Portfolios/restaurant Confusion/contactus.html
  Web Dev Projects_or_Portfolios/restaurant Confusion/css/style.css
  Web Dev Projects_or_Portfolios/restaurant Confusion/css/styles.css
  Web Dev Projects_or_Portfolios/restaurant Confusion/css/styles.less
  Web Dev Projects_or_Portfolios/restaurant Confusion/css/stylesa.css
  Web Dev Projects_or_Portfolios/restaurant Confusion/css/stylesa.scss
  Web Dev Projects_or_Portfolios/restaurant Confusion/debug.log
  Web Dev Projects_or_Portfolios/restaurant Confusion/img/.DS_Store
  Web Dev Projects_or_Portfolios/restaurant Confusion/img/alberto.png
  Web Dev Projects_or_Portfolios/restaurant Confusion/img/buffet.png
  Web Dev Projects_or_Portfolios/restaurant Confusion/img/logo.png
  Web Dev Projects_or_Portfolios/restaurant Confusion/img/uthappizza.png
  Web Dev Projects_or_Portfolios/restaurant Confusion/index.html
  Web Dev Projects_or_Portfolios/restaurant Confusion/js/scripts.js
  Web Dev Projects_or_Portfolios/restaurant Confusion/package-lock.json
  Web Dev Projects_or_Portfolios/restaurant Confusion/package.json
Labels: hacktoberfest-accepted

#223 Removed and updated all the clutter
  .idea/.gitignore
  .idea/Hacktoberfest2021_awesome-projects.iml
  .idea/modules.xml
  .idea/vcs.xml
  Awesome Javascript Projects_Scripts/Basic Background Generator/Readme.md
  Awesome Javascript Projects_Scripts/Basic Background Generator/index.html
  Awesome Javascript Projects_Scripts/Basic Background Generator/script.js
  Awesome Javascript Projects_Scripts/Basic Background Generator/style.css
  Awesome Javascript Projects_Scripts/TodoList/index.html
  Awesome Javascript Projects_Scripts/TodoList/script.js
  Awesome Javascript Projects_Scripts/TodoList/style.css
  Stunning clones/Youtube-Clone/README.md
  Stunning clones/Youtube-Clone/Resources/favicon_32x32.png
  Stunning clones/Youtube-Clone/Resources/youtube_logo.png
  Stunning clones/Youtube-Clone/Resources/youtube_logo.webp
  Stunning clones/Youtube-Clone/css/styles.css
  Stunning clones/Youtube-Clone/index.html
  Stunning clones/project_doc.md
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#78 face mask detection via haarcascade
  ML Projects/face mask detection via haarcascade/haarcascade_eye.xml
  ML Projects/face mask detection via haarcascade/haarcascade_frontalface_default.xml
  ML Projects/face mask detection via haarcascade/haarcascade_mcs_mouth.xml
  ML Projects/face mask detection via haarcascade/mask detect final.ipynb
  ML Projects/face mask detection via haarcascade/project_doc.md
Labels: hacktoberfest-accepted

#224 Added advanced Snake game
  HTML projects/Snake Game
  HTML projects/project_doc.md
  Javascript framework And Library project/Angular.js/Project_doc.md
  Javascript framework And Library project/Angular2+/Project_doc.md
  Javascript framework And Library project/React.js/Project_doc.md
  Javascript framework And Library project/React.js/game-of-life/README.md
  Javascript framework And Library project/React.js/game-of-life/package-lock.json
  Javascript framework And Library project/React.js/game-of-life/package.json
  Javascript framework And Library project/React.js/game-of-life/public/game_of_life.jpg
  Javascript framework And Library project/React.js/game-of-life/public/index.html
  Javascript framework And Library project/React.js/game-of-life/public/manifest.json
  Javascript framework And Library project/React.js/game-of-life/server.js
  Javascript framework And Library project/React.js/game-of-life/src/App.js
  Javascript framework And Library project/React.js/game-of-life/src/index.js
  Javascript framework And Library project/React.js/game-of-life/src/index.scss
  Javascript framework And Library project/React.js/game-of-life/src/serviceWorker.js
  Javascript framework And Library project/Vue.js/Project_doc.md
  README.md
Labels: hacktoberfest-accepted

#225 Updated readme with new rules
  README.md
Labels: hacktoberfest-accepted, Great

#228 added candy crush project
  Awesome Javascript Projects_Scripts/Candy Crush/.vscode/settings.json
  Awesome Javascript Projects_Scripts/Candy Crush/assets/css/style.css
  Awesome Javascript Projects_Scripts/Candy Crush/assets/images/blue-candy.png
  Awesome Javascript Projects_Scripts/Candy Crush/assets/images/green-candy.png
  Awesome Javascript Projects_Scripts/Candy Crush/assets/images/orange-candy.png
  Awesome Javascript Projects_Scripts/Candy Crush/assets/images/purple-candy.png
  Awesome Javascript Projects_Scripts/Candy Crush/assets/images/red-candy.png
  Awesome Javascript Projects_Scripts/Candy Crush/assets/images/yellow-candy.png
  Awesome Javascript Projects_Scripts/Candy Crush/assets/js/main.js
  Awesome Javascript Projects_Scripts/Candy Crush/index.html
  Awesome Javascript Projects_Scripts/Candy Crush/readme.md
Labels: hacktoberfest-accepted

#230 MatLab project Fuzzy Logic
  MatLab Projects/FuzzyLogicTipCalculator/FuncGauss.m
  MatLab Projects/FuzzyLogicTipCalculator/MatlabFuzzy1.m
Labels: hacktoberfest-accepted

#236 Basic Calculator
  HTML projects/Calculator
Labels: hacktoberfest-accepted

#238 added E-Newspaper python script
  Amazing Python Projects_Scripts/E-Newspaper/README.md
  Amazing Python Projects_Scripts/E-Newspaper/main.py
  Amazing Python Projects_Scripts/E-Newspaper/requirements.txt
  Amazing Python Projects_Scripts/E-Newspaper/screenshot/sample.jpg
Labels: hacktoberfest-accepted

#232 Updated the projrct_doc.md and readme files as instructed
  Web Dev Projects_or_Portfolios/Blogging/Pictures/background.jpg
  Web Dev Projects_or_Portfolios/Blogging/README.md
  Web Dev Projects_or_Portfolios/Blogging/assets/styles.css
  Web Dev Projects_or_Portfolios/Blogging/blog.html
  Web Dev Projects_or_Portfolios/Blogging/index.html
  Web Dev Projects_or_Portfolios/Project_doc.md
Labels: hacktoberfest, hacktoberfest-accepted

#270 Python Pong Game
  Amazing Python Projects_Scripts/Pong/Pong.py
  Amazing Python Projects_Scripts/Pong/__pycache__/Pong.cpython-36.pyc
  Amazing Python Projects_Scripts/Pong/bounce.wav
  Amazing Python Projects_Scripts/Pong/readme.md
Labels: hacktoberfest, hacktoberfest-accepted

#269 Added navbar and login buttons for webs/stock market sim.
  Web Dev Projects_or_Portfolios/Stock Market Simulator/client/package-lock.json
  Web Dev Projects_or_Portfolios/Stock Market Simulator/client/package.json
  Web Dev Projects_or_Portfolios/Stock Market Simulator/client/public/index.html
  Web Dev Projects_or_Portfolios/Stock Market Simulator/client/src/App.js
  Web Dev Projects_or_Portfolios/Stock Market Simulator/client/src/assets/liquid-cheese.svg
  Web Dev Projects_or_Portfolios/Stock Market Simulator/client/src/components/Home/Navbar.js
  Web Dev Projects_or_Portfolios/Stock Market Simulator/client/src/pages/Home.js
  Web Dev Projects_or_Portfolios/Stock Market Simulator/client/src/style/Home/Navbar.css
Labels: hacktoberfest, hacktoberfest-accepted

#253 Drum Kit
  Web Dev Projects_or_Portfolios/Drum Kit/.DS_Store
  Web Dev Projects_or_Portfolios/Drum Kit/images/crash.png
  Web Dev Projects_or_Portfolios/Drum Kit/images/kick.png
  Web Dev Projects_or_Portfolios/Drum Kit/images/snare.png
  Web Dev Projects_or_Portfolios/Drum Kit/images/tom1.png
  Web Dev Projects_or_Portfolios/Drum Kit/images/tom2.png
  Web Dev Projects_or_Portfolios/Drum Kit/images/tom3.png
  Web Dev Projects_or_Portfolios/Drum Kit/images/tom4.png
  Web Dev Projects_or_Portfolios/Drum Kit/index.html
  Web Dev Projects_or_Portfolios/Drum Kit/index.js
  Web Dev Projects_or_Portfolios/Drum Kit/sounds/crash.mp3
  Web Dev Projects_or_Portfolios/Drum Kit/sounds/kick-bass.mp3
  Web Dev Projects_or_Portfolios/Drum Kit/sounds/snare.mp3
  Web Dev Projects_or_Portfolios/Drum Kit/sounds/tom-1.mp3
  Web Dev Projects_or_Portfolios/Drum Kit/sounds/tom-2.mp3
  Web Dev Projects_or_Portfolios/Drum Kit/sounds/tom-3.mp3
  Web Dev Projects_or_Portfolios/Drum Kit/sounds/tom-4.mp3
  Web Dev Projects_or_Portfolios/Drum Kit/styles.css
Labels: hacktoberfest, hacktoberfest-accepted

#239 Added Rainfall Pattern Prediction project
  ML Projects/Rainfall-Pattern-Prediction-India/README.md
  ML Projects/Rainfall-Pattern-Prediction-India/Rainfall-pattern-prediction.ipynb
Labels: hacktoberfest, hacktoberfest-accepted

#268 Copy Command
  Amazing Python Projects_Scripts/Inventory Management System using JSON/image.png
  Amazing Python Projects_Scripts/Inventory Management System using JSON/ims.ipynb
  Amazing Python Projects_Scripts/Inventory Management System using JSON/readme.md
  Amazing Python Projects_Scripts/Inventory Management System using JSON/records.json
  Amazing Python Projects_Scripts/Inventory Management System using JSON/sales.json
  Amazing Python Projects_Scripts/Project_doc.md
  Unique C++ Projects/Copy.c
  Unique C++ Projects/Project_doc.md
Labels: hacktoberfest, hacktoberfest-accepted

#276 Simple Js project
  Awesome Javascript Projects_Scripts/mouse hover/index.html
  Awesome Javascript Projects_Scripts/mouse hover/style.css
Labels: hacktoberfest, hacktoberfest-accepted, Great

#256 Added 2048 Game
  Unique C++ Projects/2048.cpp
  Unique C++ Projects/Project_doc.md
Labels: hacktoberfest, hacktoberfest-accepted

#273 Added Javascript Higher Order Functions
  JavaScipt Higher order Functions/README.md
  JavaScipt Higher order Functions/additional_array_functions.js
  JavaScipt Higher order Functions/higher_order_functions_arrays.js
Labels: hacktoberfest, hacktoberfest-accepted

#288 Dad Jokes
  Web Dev Projects_or_Portfolios/Dad Jokes/index.html
  Web Dev Projects_or_Portfolios/Dad Jokes/readme.md
  Web Dev Projects_or_Portfolios/Dad Jokes/script.js
  Web Dev Projects_or_Portfolios/Dad Jokes/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#280 Number System Conversion Project - C++
  Unique C++ Projects/Number System Conversion with Cryptography/README.md
  Unique C++ Projects/Number System Conversion with Cryptography/nsc.cpp
  Unique C++ Projects/Number System Conversion with Cryptography/nsc.exe
  Unique C++ Projects/Number System Conversion with Cryptography/nsc.o
Labels: hacktoberfest, hacktoberfest-accepted

#274 quotes scraping using python script
  Amazing Python Projects_Scripts/quote_scrap.py
Labels: hacktoberfest, hacktoberfest-accepted

#277 Inventory Management System
  Amazing Python Projects_Scripts/Inventory Management System with JSON/image.png
  Amazing Python Projects_Scripts/Inventory Management System with JSON/ims.ipynb
  Amazing Python Projects_Scripts/Inventory Management System with JSON/readme.md
  Amazing Python Projects_Scripts/Inventory Management System with JSON/records.json
  Amazing Python Projects_Scripts/Inventory Management System with JSON/sales.json
Labels: hacktoberfest, hacktoberfest-accepted

#290 added sentiment analysis project
  ML Projects/Sentiment Analysis/Sentiment_Analysis.ipynb
  ML Projects/Sentiment Analysis/readme.md
Labels: hacktoberfest, hacktoberfest-accepted

#252 Create S3_To_DynamoDB.py
  Amazing Python Projects_Scripts/Create S3_To_DynamoDB.py
Labels: hacktoberfest, hacktoberfest-accepted

#287 Movie app added.
  Awesome Javascript Projects_Scripts/Project_doc.md
  Awesome Javascript Projects_Scripts/movieapp/app.js
  Awesome Javascript Projects_Scripts/movieapp/fetch.js
  Awesome Javascript Projects_Scripts/movieapp/index.html
  Awesome Javascript Projects_Scripts/movieapp/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#250 torautomation project
  Amazing Python Projects_Scripts/torautomation.py
Labels: hacktoberfest, hacktoberfest-accepted

#254 create audio dataset using python
  ML Projects/Create_chunk_dataset/Convert_Mp3_2_Wav.ipynb
  ML Projects/Create_chunk_dataset/Extracting Speech from Video using Python.ipynb
  ML Projects/Create_chunk_dataset/READme.txt
  ML Projects/Create_chunk_dataset/Split_audio_into_6sec_chunk.ipynb
  ML Projects/Create_chunk_dataset/sampling_Rate.ipynb
  ML Projects/Project_doc.md
Labels: hacktoberfest, hacktoberfest-accepted

#320 Password Creator
  Awesome Javascript Projects_Scripts/Password Creator/README.md
  Awesome Javascript Projects_Scripts/Password Creator/app.js
  Awesome Javascript Projects_Scripts/Password Creator/index.html
  Awesome Javascript Projects_Scripts/Password Creator/style.css
Labels: hacktoberfest-accepted

#314 Random Quotes Generator HTML project
  HTML projects/Quotes Generator/index.html
  HTML projects/Quotes Generator/readme.md
  HTML projects/Quotes Generator/script.js
  HTML projects/Quotes Generator/style.css
Labels: hacktoberfest-accepted

#240 added a role playing game + conflicts resolved
  Amazing Python Projects_Scripts/role playing game/README.md
  Amazing Python Projects_Scripts/role playing game/game.py
  Amazing Python Projects_Scripts/role playing game/inventory.py
  Amazing Python Projects_Scripts/role playing game/magic.py
  Amazing Python Projects_Scripts/role playing game/main.py
Labels: hacktoberfest-accepted

#353 Update README.md
  README.md
Labels: good first issue, hacktoberfest-accepted

#356 Added HTML Project
  HTML projects/NetflixClone/img/background.jpg
  HTML projects/NetflixClone/img/logo.png
  HTML projects/NetflixClone/img/tab-content-1.png
  HTML projects/NetflixClone/img/tab-content-2-1.png
  HTML projects/NetflixClone/img/tab-content-2-2.png
  HTML projects/NetflixClone/img/tab-content-2-3.png
  HTML projects/NetflixClone/index.css
  HTML projects/NetflixClone/index.html
  HTML projects/NetflixClone/index.js
  HTML projects/NetflixClone/readme.md
  HTML projects/project_doc.md
Labels: hacktoberfest, hacktoberfest-accepted

#299 Hotel_cancellation_prediction
  ML Projects/Hotel_cancellation_prediction/Hotel_cancellation_prediction.ipynb
  ML Projects/Hotel_cancellation_prediction/Readme.md
Labels: hacktoberfest-accepted

#348 Added Calculator Project
  HTML projects/CALCULATOR/cal.png
  HTML projects/CALCULATOR/calculator.js
  HTML projects/CALCULATOR/index.html
  HTML projects/CALCULATOR/readme.md
  HTML projects/CALCULATOR/style.css
Labels: hacktoberfest-accepted

#243 Add Dice Simulator Script
  Amazing Python Projects_Scripts/Dice Simulator/README.md
  Amazing Python Projects_Scripts/Dice Simulator/dice.py
Labels: hacktoberfest-accepted

#255 Bookshop management system (HacktoberFest2021)
  Unique C++ Projects/Bookshop management system using file handling.cpp
  Unique C++ Projects/Readme.txt
Labels: hacktoberfest, hacktoberfest-accepted

#257 Added a file
  Amazing Python Projects_Scripts/covid.py
  caersar cipher/Readme.md
  caersar cipher/__pycache__/art.cpython-38.pyc
  caersar cipher/art.py
  caersar cipher/day8.py
  caersar cipher/project_doc.md
Labels: hacktoberfest, hacktoberfest-accepted

#369 Added my scroller animation HTML layout
  HTML projects/Scroller Activation/index.html
  HTML projects/Scroller Activation/readme.md
  HTML projects/Scroller Activation/script.js
  HTML projects/Scroller Activation/styles.css
Labels: hacktoberfest-accepted

#381 CRUD operations Spring Boot and Rest
  Incredible Java Projects/Spring_Boot_CRUD/.gitignore
  Incredible Java Projects/Spring_Boot_CRUD/.mvn/wrapper/MavenWrapperDownloader.java
  Incredible Java Projects/Spring_Boot_CRUD/.mvn/wrapper/maven-wrapper.jar
  Incredible Java Projects/Spring_Boot_CRUD/.mvn/wrapper/maven-wrapper.properties
  Incredible Java Projects/Spring_Boot_CRUD/README.md
  Incredible Java Projects/Spring_Boot_CRUD/mvnw
  Incredible Java Projects/Spring_Boot_CRUD/mvnw.cmd
  Incredible Java Projects/Spring_Boot_CRUD/pom.xml
  Incredible Java Projects/Spring_Boot_CRUD/src/main/java/com/cg/demo/BootJpaApplication.java
  Incredible Java Projects/Spring_Boot_CRUD/src/main/java/com/cg/demo/controller/Controller.java
  Incredible Java Projects/Spring_Boot_CRUD/src/main/java/com/cg/demo/dao/StudentRepo.java
  Incredible Java Projects/Spring_Boot_CRUD/src/main/java/com/cg/demo/model/Student.java
  Incredible Java Projects/Spring_Boot_CRUD/src/main/resources/application.properties
  Incredible Java Projects/Spring_Boot_CRUD/src/main/webapp/home.jsp
  Incredible Java Projects/Spring_Boot_CRUD/src/main/webapp/showAllStudent.jsp
  Incredible Java Projects/Spring_Boot_CRUD/src/main/webapp/showStudent.jsp
  Incredible Java Projects/Spring_Boot_CRUD/src/main/webapp/updateStudent.jsp
  Incredible Java Projects/Spring_Boot_CRUD/src/test/java/com/cg/demo/BootJpaApplicationTests.java
Labels: hacktoberfest-accepted

#271 Added login-page Designed using HTML and CSS
  .vscode/settings.json
  Web Dev Projects_or_Portfolios/login-page/Readme.md
  Web Dev Projects_or_Portfolios/login-page/images/Background.png
  Web Dev Projects_or_Portfolios/login-page/images/iPhone Mockup.png
  Web Dev Projects_or_Portfolios/login-page/index.html
  Web Dev Projects_or_Portfolios/login-page/style.css
Labels: hacktoberfest-accepted

#391 added c++ project GUI for snake game and database
  Unique C++ Projects/user_interface_game_database/README.md
  Unique C++ Projects/user_interface_game_database/img-1.png
  Unique C++ Projects/user_interface_game_database/img-2.png
  Unique C++ Projects/user_interface_game_database/user_interface_game_database.cpp
Labels: hacktoberfest, hacktoberfest-accepted, Great

#414 Add files via upload
  ML Projects/Skin Disease Prediction using CNN/Readme.md
  ML Projects/Skin Disease Prediction using CNN/Skin Disease Prediction CNN.ipynb
Labels: hacktoberfest, hacktoberfest-accepted

#370 Added web crawler in python
  Amazing Python Projects_Scripts/Webcrawler/__pycache__/demo.cpython-39.pyc
  Amazing Python Projects_Scripts/Webcrawler/__pycache__/domain.cpython-39.pyc
  Amazing Python Projects_Scripts/Webcrawler/__pycache__/link_finder.cpython-39.pyc
  Amazing Python Projects_Scripts/Webcrawler/__pycache__/spider.cpython-39.pyc
  Amazing Python Projects_Scripts/Webcrawler/demo.py
  Amazing Python Projects_Scripts/Webcrawler/domain.py
  Amazing Python Projects_Scripts/Webcrawler/link_finder.py
  Amazing Python Projects_Scripts/Webcrawler/main.py
  Amazing Python Projects_Scripts/Webcrawler/readme.md
  Amazing Python Projects_Scripts/Webcrawler/spider.py
  Amazing Python Projects_Scripts/Webcrawler/thesite/crawled.txt
  Amazing Python Projects_Scripts/Webcrawler/thesite/queue.txt
Labels: hacktoberfest, hacktoberfest-accepted

#416 Voice Assistant
  ML Projects/Voice Assistant/Readme.md
  ML Projects/Voice Assistant/speech.py
Labels: hacktoberfest, hacktoberfest-accepted, Great

#413 Prannov
  ML Projects/READMEkerasproject.md
  ML Projects/Regression_with_Keras.ipynb
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#417 Heart Disease prediction using ML
  ML Projects/Heart Disease Prediction using ML/Heart Disease Classification.ipynb
  ML Projects/Heart Disease Prediction using ML/Readme.md
Labels: hacktoberfest, hacktoberfest-accepted

#282 Adding Web Camera Capture Project
  Web Dev Projects_or_Portfolios/Project_doc.md
  Web Dev Projects_or_Portfolios/Web-Cam-Capture/Click On Take ScreenShot Button.png
  Web Dev Projects_or_Portfolios/Web-Cam-Capture/index.html
  Web Dev Projects_or_Portfolios/Web-Cam-Capture/script.js
  Web Dev Projects_or_Portfolios/Web-Cam-Capture/style.css
  Web Dev Projects_or_Portfolios/Web-Cam-Capture/tempCodeRunnerFile.js
Labels: hacktoberfest, hacktoberfest-accepted

#286 Added my python Project
  Amazing Python Projects_Scripts/Dice_Stimular/dice.py
  Amazing Python Projects_Scripts/Dice_Stimular/dice1.jfif
  Amazing Python Projects_Scripts/Dice_Stimular/dice2.jfif
  Amazing Python Projects_Scripts/Dice_Stimular/dice3.jfif
  Amazing Python Projects_Scripts/Dice_Stimular/dice4.jfif
  Amazing Python Projects_Scripts/Dice_Stimular/dice5.jfif
  Amazing Python Projects_Scripts/Dice_Stimular/dice6.jfif
  Amazing Python Projects_Scripts/Project_doc.md
Labels: hacktoberfest, hacktoberfest-accepted

#289 midpoint circle drawing algorithm added
  Incredible Java Projects/Circle drawing applet/MidpointCircle.java
  Incredible Java Projects/Circle drawing applet/readme.md
Labels: hacktoberfest, hacktoberfest-accepted

#420 Start UP analysis using ANN
  ML Projects/Start UP analysis using ANN/Readme.md
  ML Projects/Start UP analysis using ANN/Start_Up_Analysis_using_ANN.py
  ML Projects/Start UP analysis using ANN/app.py
  ML Projects/Start UP analysis using ANN/regression.h5.py
  ML Projects/Start UP analysis using ANN/regressor.h5
Labels: hacktoberfest, hacktoberfest-accepted, Great

#390 added basic chat application made using socket.io
  Web Dev Projects_or_Portfolios/Socket Chat App/README.md
  Web Dev Projects_or_Portfolios/Socket Chat App/package-lock.json
  Web Dev Projects_or_Portfolios/Socket Chat App/package.json
  Web Dev Projects_or_Portfolios/Socket Chat App/public/chat.html
  Web Dev Projects_or_Portfolios/Socket Chat App/public/css/styles.css
  Web Dev Projects_or_Portfolios/Socket Chat App/public/css/styles.min.css
  Web Dev Projects_or_Portfolios/Socket Chat App/public/img/Screenshot1.png
  Web Dev Projects_or_Portfolios/Socket Chat App/public/img/Screenshot2.png
  Web Dev Projects_or_Portfolios/Socket Chat App/public/img/favicon.png
  Web Dev Projects_or_Portfolios/Socket Chat App/public/index.html
  Web Dev Projects_or_Portfolios/Socket Chat App/public/js/chat.js
  Web Dev Projects_or_Portfolios/Socket Chat App/src/index.js
  Web Dev Projects_or_Portfolios/Socket Chat App/src/utils/messages.js
  Web Dev Projects_or_Portfolios/Socket Chat App/src/utils/users.js
Labels: hacktoberfest, hacktoberfest-accepted, Great

#421 Spam Classifier using NLP
  ML Projects/Spam Classifier using NLP/Readme.md
  ML Projects/Spam Classifier using NLP/Spam_Classifier.py
Labels: hacktoberfest, hacktoberfest-accepted

#350 Added Pomodoro timer python script
  Amazing Python Projects_Scripts/PomodoroTimer/Pomodoro.py
  Amazing Python Projects_Scripts/PomodoroTimer/README.md
Labels: hacktoberfest, hacktoberfest-accepted

#422 Chronic Kidney Disease prediction
  ML Projects/Chronic Kidney Disease prediction/Readme.md
  ML Projects/Chronic Kidney Disease prediction/predicting-chronic-kidney-disease (1).ipynb
Labels: hacktoberfest, hacktoberfest-accepted, Great

#341 added show search JS project
  Awesome Javascript Projects_Scripts/Show Searcher/README.md
  Awesome Javascript Projects_Scripts/Show Searcher/index.html
  Awesome Javascript Projects_Scripts/Show Searcher/script.js
Labels: hacktoberfest, hacktoberfest-accepted

#433 Added Snake Game in Amazing Python Project_Scripts using Pygame
  Amazing Python Projects_Scripts/Snake Game/README.md
  Amazing Python Projects_Scripts/Snake Game/game.py
  Amazing Python Projects_Scripts/Snake Game/highscore.txt
Labels: hacktoberfest, hacktoberfest-accepted, Great

#423 RGB-Color-Guessing-Game
  Awesome Javascript Projects_Scripts/RGB-Color-Guessing-Game/README.md
  Awesome Javascript Projects_Scripts/RGB-Color-Guessing-Game/RGB-Game.png
  Awesome Javascript Projects_Scripts/RGB-Color-Guessing-Game/index.html
  Awesome Javascript Projects_Scripts/RGB-Color-Guessing-Game/index.js
  Awesome Javascript Projects_Scripts/RGB-Color-Guessing-Game/sounds/Correct.mp3
  Awesome Javascript Projects_Scripts/RGB-Color-Guessing-Game/sounds/Wrong.mp3
  Awesome Javascript Projects_Scripts/RGB-Color-Guessing-Game/styles.css
Labels: hacktoberfest-accepted

#439 Added guessing game es6 js
  Awesome Javascript Projects_Scripts/Guess-my-technology/Capture.PNG
  Awesome Javascript Projects_Scripts/Guess-my-technology/Capture1.PNG
  Awesome Javascript Projects_Scripts/Guess-my-technology/README.md
  Awesome Javascript Projects_Scripts/Guess-my-technology/scramble.html
Labels: hacktoberfest-accepted

#397 Added WebDev project - Assignment Submisssion Form
  Web Dev Projects_or_Portfolios/Assignment-Submission_form/.firebaserc
  Web Dev Projects_or_Portfolios/Assignment-Submission_form/.gitignore
  Web Dev Projects_or_Portfolios/Assignment-Submission_form/README.md
  Web Dev Projects_or_Portfolios/Assignment-Submission_form/firebase-debug.log
  Web Dev Projects_or_Portfolios/Assignment-Submission_form/firebase.json
  Web Dev Projects_or_Portfolios/Assignment-Submission_form/firestore.indexes.json
  Web Dev Projects_or_Portfolios/Assignment-Submission_form/firestore.rules
  Web Dev Projects_or_Portfolios/Assignment-Submission_form/netlify.toml
  Web Dev Projects_or_Portfolios/Assignment-Submission_form/package-lock.json
  Web Dev Projects_or_Portfolios/Assignment-Submission_form/package.json
  Web Dev Projects_or_Portfolios/Assignment-Submission_form/public/favicon.ico
  Web Dev Projects_or_Portfolios/Assignment-Submission_form/public/form-logo.png
  Web Dev Projects_or_Portfolios/Assignment-Submission_form/public/index.html
  Web Dev Projects_or_Portfolios/Assignment-Submission_form/public/logo192.png
  Web Dev Projects_or_Portfolios/Assignment-Submission_form/public/logo512.png
  Web Dev Projects_or_Portfolios/Assignment-Submission_form/public/manifest.json
  Web Dev Projects_or_Portfolios/Assignment-Submission_form/public/robots.txt
  Web Dev Projects_or_Portfolios/Assignment-Submission_form/src/App.css
  Web Dev Projects_or_Portfolios/Assignment-Submission_form/src/App.js
  Web Dev Projects_or_Portfolios/Assignment-Submission_form/src/App.test.js
  Web Dev Projects_or_Portfolios/Assignment-Submission_form/src/assets/images/form-logo.png
  Web Dev Projects_or_Portfolios/Assignment-Submission_form/src/assets/images/hackathon.png
  Web Dev Projects_or_Portfolios/Assignment-Submission_form/src/components/form.css
  Web Dev Projects_or_Portfolios/Assignment-Submission_form/src/components/form.js
  Web Dev Projects_or_Portfolios/Assignment-Submission_form/src/components/submissions.css
  Web Dev Projects_or_Portfolios/Assignment-Submission_form/src/components/submissions.js
  Web Dev Projects_or_Portfolios/Assignment-Submission_form/src/components/success.css
  Web Dev Projects_or_Portfolios/Assignment-Submission_form/src/components/success.js
  Web Dev Projects_or_Portfolios/Assignment-Submission_form/src/firebase-config.js
  Web Dev Projects_or_Portfolios/Assignment-Submission_form/src/index.css
  Web Dev Projects_or_Portfolios/Assignment-Submission_form/src/index.js
  Web Dev Projects_or_Portfolios/Assignment-Submission_form/src/logo.svg
  Web Dev Projects_or_Portfolios/Assignment-Submission_form/src/reportWebVitals.js
  Web Dev Projects_or_Portfolios/Assignment-Submission_form/src/setupTests.js
  Web Dev Projects_or_Portfolios/Assignment-Submission_form/storage.rules
Labels: hacktoberfest-accepted

#444 Updated the readme
  README.md
Labels: hacktoberfest-accepted

#496 Python Virtual Wriring Board
  Amazing Python Projects_Scripts/Virtual Writing Board/README.md
  Amazing Python Projects_Scripts/Virtual Writing Board/tools.png
  Amazing Python Projects_Scripts/Virtual Writing Board/tools1.png
  Amazing Python Projects_Scripts/Virtual Writing Board/tools2.png
  Amazing Python Projects_Scripts/Virtual Writing Board/virtual_writing_board.py
Labels: hacktoberfest, hacktoberfest-accepted, Great

#495 Added Minesweeper Project
  Unique C++ Projects/Minesweeper/minesweeper.cpp
  Unique C++ Projects/Minesweeper/readme.md
Labels: hacktoberfest, hacktoberfest-accepted, Great

#485 Added Phishing Detection Using Machine Learning
  ML Projects/Phishing -Detection-Using-Machine-Learning/Model Evaluation.ipynb
  ML Projects/Phishing -Detection-Using-Machine-Learning/README.md
Labels: hacktoberfest-accepted

#479 Transpose the Image
  Amazing Python Projects_Scripts/Project_doc.md
  Amazing Python Projects_Scripts/Transpose the Image/Image_Transpose.py
Labels: hacktoberfest-accepted
